### ISSUE TITLE
Rotating Screen Issue

### ISSUE THREAD

**Issue by AlanPeters** [AlanPeters/AndroidTurnSignals#1]
The buttons states are not transmitted to the bluetooth device after the screen orientation is changed. 
Button objects were changed from static to instance variables in a recent commit. Probably is part of the issue.

**Comment by redragonx** [comment]
This is pretty easy to fix, make a fragment for the activity you are using and call setRetation(true) in onCreate() of the activity. This will keep the fragment in memory while it changes the layout. 

Although, this won't work when the UI becomes advanced.

**Comment by AlanPeters** [comment]
I think it will be fixed when I do some more enhancements. I am working on a class called Signal to track the status of the the brake lights and signals. Should be able to have the thread reference this and make sure the reference is stored in a bundle when the activity is destroyed the recreated.

**Comment by AlanPeters** [comment]
Store state in signals object and gets state when the buttons are reconnected.
